name: frontend
description: "WanderGem"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  http: 1.3.0
  google_generative_ai: ^0.2.2
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.8.0
  connectivity_plus: ^5.0.2
  
  
  mapbox_maps_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/background.png
