name: frontend
description: "WanderGem"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  permission_handler: ^10.4.5
  ar_flutter_plugin: ^0.7.2 # (Check latest version on pub.dev)
  vector_math: ^2.1.4        # Required for 3D math operations
  flutter_cube: ^0.1.1
  #model_viewer: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mapbox_maps_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0


flutter:
  assets:
    - assets/3d_models/Taj_Mahal.obj/
  uses-material-design: true
  assets:
    - assets/.env
