// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhdlyYAd2YiK6ad0uNS-5nDfAyHldgZI',
    appId: '1:331392634168:web:af294cc493b45cf23905cd',
    messagingSenderId: '331392634168',
    projectId: 'wandergem-a562e',
    authDomain: 'wandergem-a562e.firebaseapp.com',
    storageBucket: 'wandergem-a562e.firebasestorage.app',
    measurementId: 'G-8Z4CZESGPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6B8DvplEd_zdz5I2NZSussF19MBMIzy0',
    appId: '1:331392634168:android:84961cd5788566483905cd',
    messagingSenderId: '331392634168',
    projectId: 'wandergem-a562e',
    storageBucket: 'wandergem-a562e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiHzFY8x7gJTIW3BB2f4vz_uQeYzwMpmQ',
    appId: '1:331392634168:ios:9fd9fa706e1c8f843905cd',
    messagingSenderId: '331392634168',
    projectId: 'wandergem-a562e',
    storageBucket: 'wandergem-a562e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiHzFY8x7gJTIW3BB2f4vz_uQeYzwMpmQ',
    appId: '1:331392634168:ios:9fd9fa706e1c8f843905cd',
    messagingSenderId: '331392634168',
    projectId: 'wandergem-a562e',
    storageBucket: 'wandergem-a562e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDhdlyYAd2YiK6ad0uNS-5nDfAyHldgZI',
    appId: '1:331392634168:web:f2a3e12a482f30163905cd',
    messagingSenderId: '331392634168',
    projectId: 'wandergem-a562e',
    authDomain: 'wandergem-a562e.firebaseapp.com',
    storageBucket: 'wandergem-a562e.firebasestorage.app',
    measurementId: 'G-3VM17HRXGM',
  );
}
